import { 
    calculateJointCenter, 
    createJointBackwall, 
    connectProxiesDiagonallyUphill, 
    connectProxiesDiagonallyDownhill,
    createJointClosure,
    mergeGeometries,
    createGeometryFromPoints
} from "./Geometry_3D_Joints_Utils.js";
import { sharedData } from "../../../Ahu3D/globals.js";

export default class Geometry_3D_Joints_Colinear {
    createParallelJoint(intersection, pairDirection, joint) {
        const geometries = [];

        if(pairDirection == "vertical") {
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxy1.coordinates[1],
                    joint.down.proxy1.coordinates[1],
                    joint.down.proxy1.coordinates[5],
                    joint.up.proxy1.coordinates[5]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxy1.coordinates[0],
                    joint.down.proxy1.coordinates[0],
                    joint.down.proxy1.coordinates[4],
                    joint.up.proxy1.coordinates[4]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxy1.coordinates[0],
                    joint.down.proxy1.coordinates[3],
                    joint.down.proxy1.coordinates[2],
                    joint.up.proxy1.coordinates[1]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxy1.coordinates[4],
                    joint.down.proxy1.coordinates[4],
                    joint.down.proxy1.coordinates[5],
                    joint.up.proxy1.coordinates[5]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxyOriginal1.coordinates[7],
                    joint.up.proxyOriginal2.coordinates[7],
                    joint.up.proxy2.coordinates[7],
                    joint.up.proxy1.coordinates[7]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.down.proxyOriginal1.coordinates[5],
                    joint.down.proxyOriginal2.coordinates[5],
                    joint.down.proxy2.coordinates[5],
                    joint.down.proxy1.coordinates[5]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.down.proxyOriginal1.coordinates[4],
                    joint.down.proxyOriginal2.coordinates[4],
                    joint.down.proxyOriginal2.coordinates[5],
                    joint.down.proxyOriginal1.coordinates[5]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxy1.coordinates[4],
                    joint.down.proxy2.coordinates[4],
                    joint.down.proxy2.coordinates[5],
                    joint.up.proxy1.coordinates[5]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxy2.coordinates[1],
                    joint.down.proxy2.coordinates[1],
                    joint.down.proxy2.coordinates[5],
                    joint.up.proxy2.coordinates[5]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxy2.coordinates[0],
                    joint.down.proxy2.coordinates[0],
                    joint.down.proxy2.coordinates[4],
                    joint.up.proxy2.coordinates[4]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxy2.coordinates[0],
                    joint.down.proxy2.coordinates[3],
                    joint.down.proxy2.coordinates[2],
                    joint.up.proxy2.coordinates[1]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.up.proxy2.coordinates[4],
                    joint.down.proxy2.coordinates[4],
                    joint.down.proxy2.coordinates[5],
                    joint.up.proxy2.coordinates[5]
                )
            );
        }
        if(pairDirection == "horizontal") {
            geometries.push(
                createGeometryFromPoints(
                    joint.left.proxy1.coordinates[2],
                    joint.right.proxy1.coordinates[2],
                    joint.right.proxy1.coordinates[6],
                    joint.left.proxy1.coordinates[6]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.left.proxy1.coordinates[1],
                    joint.right.proxy1.coordinates[1],
                    joint.right.proxy1.coordinates[5],
                    joint.left.proxy1.coordinates[5]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.left.proxy1.coordinates[1],
                    joint.right.proxy1.coordinates[0],
                    joint.right.proxy1.coordinates[3],
                    joint.left.proxy1.coordinates[2]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.left.proxy1.coordinates[5],
                    joint.right.proxy1.coordinates[5],
                    joint.right.proxy1.coordinates[6],
                    joint.left.proxy1.coordinates[6]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.right.proxyOriginal1.coordinates[5],
                    joint.right.proxyOriginal2.coordinates[5],
                    joint.right.proxy2.coordinates[5],
                    joint.right.proxy1.coordinates[5]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.right.proxyOriginal1.coordinates[6],
                    joint.right.proxyOriginal2.coordinates[6],
                    joint.right.proxy2.coordinates[6],
                    joint.right.proxy1.coordinates[6]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.right.proxyOriginal1.coordinates[5],
                    joint.right.proxyOriginal2.coordinates[5],
                    joint.right.proxyOriginal2.coordinates[6],
                    joint.right.proxyOriginal1.coordinates[6]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.left.proxy1.coordinates[5],
                    joint.right.proxy2.coordinates[5],
                    joint.right.proxy2.coordinates[6],
                    joint.left.proxy1.coordinates[6]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.left.proxy2.coordinates[2],
                    joint.right.proxy2.coordinates[2],
                    joint.right.proxy2.coordinates[6],
                    joint.left.proxy2.coordinates[6]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.left.proxy2.coordinates[1],
                    joint.right.proxy2.coordinates[1],
                    joint.right.proxy2.coordinates[5],
                    joint.left.proxy2.coordinates[5]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.left.proxy2.coordinates[1],
                    joint.right.proxy2.coordinates[0],
                    joint.right.proxy2.coordinates[3],
                    joint.left.proxy2.coordinates[2]
                )
            );
            geometries.push(
                createGeometryFromPoints(
                    joint.left.proxy2.coordinates[5],
                    joint.right.proxy2.coordinates[5],
                    joint.right.proxy2.coordinates[6],
                    joint.left.proxy2.coordinates[6]
                )
            );
        }

        const newMergedGeometry = mergeGeometries(geometries);
        return newMergedGeometry;
    }
}